import Navigation from "../components/navigation";
import "../app/styles/global.css";
export const metadata = {
  title: "Home | Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
